# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ugeeBinarySymReal <- function(n1, n2, n1_n2, effective_n, ymat, xmat, cat, cts, tol = 1e-3, maxiter = 50L) {
    .Call(`_MicrobiomeFRM_ugeeBinarySymReal`, n1, n2, n1_n2, effective_n, ymat, xmat, cat, cts, tol, maxiter)
}

chisq_stat <- function(X, theta, Sigma) {
    .Call(`_MicrobiomeFRM_chisq_stat`, X, theta, Sigma)
}

dist2mat <- function(x, bf) {
    .Call(`_MicrobiomeFRM_dist2mat`, x, bf)
}

ugeecov_cate_cont_exp2_new <- function(dmatY, cat, cts, tol = 1e-3, maxiter = 25L) {
    .Call(`_MicrobiomeFRM_ugeecov_cate_cont_exp2_new`, dmatY, cat, cts, tol, maxiter)
}

ugeeSym_cont_cate_cov <- function(ymat, xmat, cat, cts, tol = 1e-3, maxiter = 25L) {
    .Call(`_MicrobiomeFRM_ugeeSym_cont_cate_cov`, ymat, xmat, cat, cts, tol, maxiter)
}

